version: '3.9' 

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./test.db
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: fastapi_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: example
#       POSTGRES_DB: test
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: